doctrine:
    orm:
        mappings:
            BasicEntities:
                type: annotation
                dir: '%kernel.project_dir%/vendor/runroom/samples-bundle/src/BasicEntities/Entity'
                prefix: Runroom\SamplesBundle\BasicEntities\Entity
                is_bundle: false
            Forms:
                type: annotation
                dir: '%kernel.project_dir%/vendor/runroom/samples-bundle/src/Forms/Entity'
                prefix: Runroom\SamplesBundle\Forms\Entity
                is_bundle: false

sonata_admin:
    dashboard:
        groups:
            demo:
                label: Runroom Samples
                items:
                    - Runroom\SamplesBundle\BasicEntities\Admin\BookAdmin
                    - Runroom\SamplesBundle\BasicEntities\Admin\CategoryAdmin
                    - Runroom\SamplesBundle\Forms\Admin\ContactAdmin

fos_elastica:
    indexes:
        books:
            types:
                default:
                    properties:
                        id: null
                    persistence:
                        driver: orm
                        model: Runroom\SamplesBundle\BasicEntities\Entity\Book
                        listener:
                            defer: true
                            logger: true
                        elastica_to_model_transformer:
                            ignore_missing: true
