doctrine:
    orm:
        mappings:
            BasicEntities:
                type: attribute
                dir: '%kernel.project_dir%/vendor/runroom/samples-bundle/src/BasicEntities/Entity'
                prefix: Runroom\SamplesBundle\BasicEntities\Entity
                is_bundle: false
            Forms:
                type: attribute
                dir: '%kernel.project_dir%/vendor/runroom/samples-bundle/src/Forms/Entity'
                prefix: Runroom\SamplesBundle\Forms\Entity
                is_bundle: false

sonata_admin:
    dashboard:
        groups:
            demo:
                label: Runroom Samples
                items:
                    - Runroom\SamplesBundle\BasicEntities\Admin\BookAdmin
                    - Runroom\SamplesBundle\BasicEntities\Admin\CategoryAdmin
                    - Runroom\SamplesBundle\Forms\Admin\ContactAdmin
