name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: PHP ${{ matrix.php }} + ${{ matrix.dependencies }} + symfony ${{ matrix.symfony-require }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
        dependencies: [highest]
        symfony-require: [highest]
        include:
          - php: '7.4'
            dependencies: lowest
            symfony-require: highest
          - php: '8.1'
            dependencies: highest
            symfony-require: 4.4.*
          - php: '8.1'
            dependencies: highest
            symfony-require: 5.4.*
          - php: '8.1'
            dependencies: highest
            symfony-require: 6.0.*
          - php: '8.1'
            dependencies: highest
            symfony-require: 6.1.*
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony-require}}
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - if: matrix.symfony-require != 'highest'
        run: |
            composer global config --no-plugins allow-plugins.symfony/flex true
            composer global require --no-progress --no-scripts --no-plugins symfony/flex
      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}
      - run: vendor/bin/phpunit --coverage-clover=clover.xml
      - uses: codecov/codecov-action@v2
