name: QA

on:
  push:
    branches: [master]
  pull_request:

jobs:
  php:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3']
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: cs2pr
      - uses: ramsey/composer-install@v3
      - run: composer php-cs-fixer -- --dry-run --format=checkstyle | cs2pr
      - run: vendor/bin/phpunit
      - run: composer phpstan
      - run: composer psalm -- --php-version=8.1 --threads=$(nproc) --output-format=github --shepherd
      - run: composer normalize --no-check-lock --no-update-lock --dry-run --diff
      - run: composer validate --strict
      - run: composer rector -- --dry-run
      - run: bin/console lint:container
      - run: bin/console lint:twig templates
      - run: bin/console lint:xliff config
      - run: bin/console lint:yaml config
